torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 8 --ring_impl_type "basic" --attn_impl paro --head_idx 31 --output_csv ./attention_speedup_ulysses.csv
torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 8 --ring_impl_type "basic" --attn_impl paro --head_idx 17 --output_csv ./attention_speedup_ulysses.csv
torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 8 --ring_impl_type "basic" --attn_impl paro --head_idx 39 --output_csv ./attention_speedup_ulysses.csv
torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 8 --ring_impl_type "basic" --attn_impl paro --head_idx 35 --output_csv ./attention_speedup_ulysses.csv
torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 8 --ring_impl_type "basic" --attn_impl paro --head_idx 15 --output_csv ./attention_speedup_ulysses.csv
torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 8 --ring_impl_type "basic" --attn_impl paro --head_idx 33 --output_csv ./attention_speedup_ulysses.csv
torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 8 --ring_impl_type "basic" --attn_impl paro --head_idx 36 --output_csv ./attention_speedup_ulysses.csv


# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 0 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 1 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 2 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 3 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 4 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 5 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 6 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 7 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 8 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 9 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 10 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 11 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 12 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 13 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 14 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 15 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 16 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 17 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 18 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 19 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 20 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 21 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 22 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 23 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 24 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 25 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 26 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 27 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 28 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 29 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 30 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 31 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 32 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 33 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 34 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 35 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 36 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 37 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 38 --output_csv ./attention_speedup_ring.csv
# torchrun --nproc_per_node=8 ./test/ae.py --sp_ulysses_degree 1 --ring_impl_type "basic" --attn_impl paro --head_idx 39 --output_csv ./attention_speedup_ring.csv